// Generated by CoffeeScript 1.3.1
(function() {
  var Formwatcher, Watcher, deepExtend,
    __slice = [].slice,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  deepExtend = function() {
    var extenders, key, object, other, val, _i, _len;
    object = arguments[0], extenders = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    if (object == null) {
      return {};
    }
    for (_i = 0, _len = extenders.length; _i < _len; _i++) {
      other = extenders[_i];
      for (key in other) {
        if (!__hasProp.call(other, key)) continue;
        val = other[key];
        if (!((object[key] != null) && typeof val === "object")) {
          object[key] = val;
        } else {
          object[key] = deepExtend(object[key], val);
        }
      }
    }
    return object;
  };

  $.ender({
    uid: function() {
      var el, id;
      if (this[0] == null) {
        return null;
      }
      el = this.first();
      id = el.attr("id");
      if (id == null) {
        id = "formwatcher-uid-" + (Formwatcher.uidCounter++);
        el.attr("id", id);
      }
      return id;
    }
  }, true);

  $.ender({
    fwData: function(name, value) {
      var formwatcherAttributes;
      if (this.data("_formwatcher") == null) {
        this.data("_formwatcher", {});
      }
      if (name == null) {
        return this;
      }
      formwatcherAttributes = this.data("_formwatcher");
      if (value != null) {
        formwatcherAttributes[name] = value;
        this.data("_formwatcher", formwatcherAttributes);
        return this;
      } else {
        return formwatcherAttributes[name];
      }
    }
  }, true);

  Formwatcher = {
    version: "2.0.0-dev",
    debugging: false,
    uidCounter: 0,
    debug: function() {
      if (this.debugging && ((typeof console !== "undefined" && console !== null ? console.debug : void 0) != null)) {
        return console.debug.apply(console, arguments);
      }
    },
    getErrorsElement: function(elements, createIfNotFound) {
      var errors, input;
      input = elements.input;
      if (input.attr("name")) {
        errors = $("#" + (input.attr('name')) + "-errors");
      }
      if (!((errors != null ? errors.length : void 0) || !input.attr("id"))) {
        errors = $("#" + (input.attr('id')) + "-errors");
      }
      if (!errors || !errors.length) {
        errors = $.create("<span />");
        if (input.attr("name")) {
          errors.attr("id", input.attr("name") + "-errors");
        }
        input.after(errors);
      }
      errors.hide().addClass("errors").addClass("fw-errors");
      return errors;
    },
    getLabel: function(elements, automatchLabel) {
      var input, label;
      input = elements.input;
      label = void 0;
      if (input.attr("id")) {
        label = $("label[for=" + input.attr("id") + "]");
        if (!label.length) {
          label = undefined;
        }
      }
      if (!label && automatchLabel) {
        label = input.previous();
        window.testinput = input;
        if (!label.length || label.get(0).nodeName !== "LABEL" || (label.attr("for") != null)) {
          label = void 0;
        }
      }
      return label;
    },
    changed: function(elements, watcher) {
      var input;
      input = elements.input;
      if (!input.fwData("forceValidationOnChange") && (input.attr("type") === "checkbox" && input.fwData("previouslyChecked") === input.is(":checked")) || (input.fwData("previousValue") === input.val())) {
        return;
      }
      input.fwData("forceValidationOnChange", false);
      this.setPreviousValueToCurrentValue(elements);
      if ((input.attr("type") === "checkbox") && (input.fwData("initialyChecked") !== input.is(":checked")) || (input.attr("type") !== "checkbox") && (input.fwData("initialValue") !== input.val())) {
        Formwatcher.setChanged(elements, watcher);
      } else {
        Formwatcher.unsetChanged(elements, watcher);
      }
      if (watcher.options.validate) {
        return watcher.validateElements(elements);
      }
    },
    setChanged: function(elements, watcher) {
      var element, i, input, _i, _len;
      input = elements.input;
      if (input.fwData("changed")) {
        return;
      }
      for (element = _i = 0, _len = elements.length; _i < _len; element = ++_i) {
        i = elements[element];
        element.addClass("changed");
      }
      input.fwData("changed", true);
      if (!watcher.options.submitUnchanged) {
        Formwatcher.restoreName(elements);
      }
      if (watcher.options.submitOnChange && watcher.options.ajax) {
        return watcher.submitForm();
      }
    },
    unsetChanged: function(elements, watcher) {
      var element, i, input, _i, _len;
      input = elements.input;
      if (!input.fwData("changed")) {
        return;
      }
      for (element = _i = 0, _len = elements.length; _i < _len; element = ++_i) {
        i = elements[element];
        element.removeClass("changed");
      }
      input.fwData("changed", false);
      if (!watcher.options.submitUnchanged) {
        return Formwatcher.removeName(elements);
      }
    },
    storeInitialValue: function(elements) {
      var input;
      input = elements.input;
      if (input.attr("type") === "checkbox") {
        input.fwData("initialyChecked", input.is(":checked"));
      } else {
        input.fwData("initialValue", input.val());
      }
      return this.setPreviousValueToInitialValue(elements);
    },
    restoreInitialValue: function(elements) {
      var input;
      input = elements.input;
      if (input.attr("type") === "checkbox") {
        input.attr("checked", input.fwData("initialyChecked"));
      } else {
        input.val(input.fwData("initialValue"));
      }
      return this.setPreviousValueToInitialValue(elements);
    },
    setPreviousValueToInitialValue: function(elements) {
      var input;
      input = elements.input;
      if (input.attr("type") === "checkbox") {
        return input.fwData("previouslyChecked", input.fwData("initialyChecked"));
      } else {
        return input.fwData("previousValue", input.fwData("initialValue"));
      }
    },
    setPreviousValueToCurrentValue: function(elements) {
      var input;
      input = elements.input;
      if (input.attr("type") === "checkbox") {
        return input.fwData("previouslyChecked", input.is(":checked"));
      } else {
        return input.fwData("previousValue", input.val());
      }
    },
    removeName: function(elements) {
      var input;
      input = elements.input;
      if (input.attr("type") === "checkbox") {
        return;
      }
      if (!input.fwData("name")) {
        input.fwData("name", input.attr("name") || "");
      }
      return input.attr("name", "");
    },
    restoreName: function(elements) {
      var input;
      input = elements.input;
      if (input.attr("type") === "checkbox") {
        return;
      }
      return input.attr("name", input.fwData("name"));
    },
    Decorators: [],
    decorate: function(watcher, input) {
      var decorator;
      decorator = _.detect(watcher.decorators, function(decorator) {
        if (decorator.accepts(input)) {
          return true;
        }
      });
      if (decorator) {
        Formwatcher.debug("Decorator \"" + decorator.name + "\" found for input field \"" + input.attr("name") + "\".");
        return decorator.decorate(input);
      } else {
        return {
          input: input
        };
      }
    },
    Validators: [],
    currentWatcherId: 0,
    watchers: [],
    add: function(watcher) {
      return this.watchers[watcher.id] = watcher;
    },
    get: function(id) {
      return this.watchers[id];
    },
    getAll: function() {
      return this.watchers;
    },
    scanDocument: function() {
      var formId, handleForm, _results;
      handleForm = function(form) {
        var domOptions, formId, options;
        form = $(form);
        if (form.fwData("watcher")) {
          return;
        }
        formId = form.attr("id");
        options = {};
        if (formId ? Formwatcher.options[formId] : void 0) {
          options = Formwatcher.options[formId];
        }
        domOptions = form.data("fw");
        if (domOptions) {
          options = _.extend(options, domOptions);
        }
        return new Watcher(form, options);
      };
      $('form[data-fw], form[data-fw=""]').each(function() {
        return handleForm(this);
      });
      _results = [];
      for (formId in Formwatcher.options) {
        _results.push(handleForm($("#" + formId)));
      }
      return _results;
    },
    watch: function(form, options) {
      return $.domReady(function() {
        return new Watcher(form, options);
      });
    }
  };

  Formwatcher._ElementWatcher = (function() {

    _ElementWatcher.name = '_ElementWatcher';

    _ElementWatcher.prototype.name = "No name";

    _ElementWatcher.prototype.description = "No description";

    _ElementWatcher.prototype.nodeNames = null;

    _ElementWatcher.prototype.classNames = [];

    _ElementWatcher.prototype.defaultOptions = {};

    _ElementWatcher.prototype.options = null;

    function _ElementWatcher(watcher) {
      var _ref;
      this.watcher = watcher;
      this.options = deepExtend({}, this.defaultOptions, (_ref = watcher.options[this.name]) != null ? _ref : {});
    }

    _ElementWatcher.prototype.accepts = function(input) {
      if ((this.watcher.options[this.name] != null) && this.watcher.options[this.name] === false) {
        return false;
      }
      return _.any(this.nodeNames, function(nodeName) {
        return input.get(0).nodeName === nodeName;
      }) && _.all(this.classNames, function(className) {
        return input.hasClass(className);
      });
    };

    return _ElementWatcher;

  })();

  Formwatcher.Decorator = (function(_super) {

    __extends(Decorator, _super);

    Decorator.name = 'Decorator';

    function Decorator() {
      return Decorator.__super__.constructor.apply(this, arguments);
    }

    Decorator.prototype.decorate = function(watcher, input) {
      return {
        input: input
      };
    };

    return Decorator;

  })(Formwatcher._ElementWatcher);

  Formwatcher.Validator = (function(_super) {

    __extends(Validator, _super);

    Validator.name = 'Validator';

    function Validator() {
      return Validator.__super__.constructor.apply(this, arguments);
    }

    Validator.prototype.nodeNames = ["INPUT", "TEXTAREA", "SELECT"];

    Validator.prototype.validate = function(sanitizedValue, input) {
      return true;
    };

    Validator.prototype.sanitize = function(value) {
      return value;
    };

    return Validator;

  })(Formwatcher._ElementWatcher);

  Formwatcher.defaultOptions = {
    ajax: false,
    validate: true,
    submitOnChange: false,
    submitUnchanged: true,
    submitFormIfAllUnchanged: false,
    resetFormAfterSubmit: false,
    automatchLabel: true,
    responseCheck: function(data) {
      return !data;
    },
    onSubmit: function() {},
    onSuccess: function(data) {},
    onError: function(data) {
      return alert(data);
    }
  };

  Formwatcher.options = {};

  Watcher = (function() {

    Watcher.name = 'Watcher';

    function Watcher(form, options) {
      var hiddenSubmitButtonElement, submitButtons,
        _this = this;
      this.form = typeof form === "string" ? $("#" + form) : $(form);
      if (this.form.length < 1) {
        throw "Form element not found.";
      } else if (this.form.length > 1) {
        throw "The jQuery contained more than 1 element.";
      } else {
        if (this.form.get(0).nodeName !== "FORM") {
          throw "The element was not a form.";
        }
      }
      this.allElements = [];
      this.id = Formwatcher.currentWatcherId++;
      Formwatcher.add(this);
      this.observers = {};
      this.form.fwData("watcher", this);
      this.form.fwData("originalAction", this.form.attr("action") || "").attr("action", "javascript:undefined;");
      this.options = deepExtend({}, Formwatcher.defaultOptions, options || {});
      this.decorators = [];
      this.validators = [];
      _.each(Formwatcher.Decorators, function(Decorator) {
        return _this.decorators.push(new Decorator(_this));
      });
      _.each(Formwatcher.Validators, function(Validator) {
        return _this.validators.push(new Validator(_this));
      });
      this.observe("submit", this.options.onSubmit);
      this.observe("success", this.options.onSuccess);
      this.observe("error", this.options.onError);
      $(":input", this.form).each(function(input) {
        var element, elements, errorsElement, i, label, onchangeFunction, validateElementsFunction, _results;
        input = $(input);
        if (!input.fwData("initialized")) {
          if (input.attr("type") === "hidden") {
            return input.fwData("forceSubmission", true);
          } else {
            elements = Formwatcher.decorate(_this, input);
            if (elements.input.get() !== input.get()) {
              elements.input.attr("class", input.attr("class"));
              input = elements.input;
            }
            if (!elements.label) {
              label = Formwatcher.getLabel(elements, _this.options.automatchLabel);
              if (label) {
                elements.label = label;
              }
            }
            if (!elements.errors) {
              errorsElement = Formwatcher.getErrorsElement(elements, true);
              elements.errors = errorsElement;
            }
            _this.allElements.push(elements);
            input.fwData("validators", []);
            _.each(_this.validators, function(validator) {
              if (validator.accepts(input, _this)) {
                Formwatcher.debug("Validator \"" + validator.name + "\" found for input field \"" + input.attr("name") + "\".");
                return input.fwData("validators").push(validator);
              }
            });
            Formwatcher.storeInitialValue(elements);
            if (input.val() === null || !input.val()) {
              for (i in elements) {
                element = elements[i];
                element.addClass("empty");
              }
            }
            if (!_this.options.submitUnchanged) {
              Formwatcher.removeName(elements);
            }
            onchangeFunction = _.bind(Formwatcher.changed, Formwatcher, elements, _this);
            validateElementsFunction = _.bind(_this.validateElements, _this, elements, true);
            _results = [];
            for (i in elements) {
              element = elements[i];
              element.on("focus", function() {
                return element.addClass("focus");
              });
              element.on("blur", function() {
                return element.removeClass("focus");
              });
              element.on("change", onchangeFunction);
              element.on("blur", onchangeFunction);
              _results.push(element.on("keyup", validateElementsFunction));
            }
            return _results;
          }
        }
      });
      submitButtons = $(":submit", this.form);
      hiddenSubmitButtonElement = $.create('<input type="hidden" name="" value="" />');
      this.form.append(hiddenSubmitButtonElement);
      submitButtons.each(function(element) {
        element = $(element);
        return element.click(function(e) {
          hiddenSubmitButtonElement.attr("name", element.attr("name") || "").attr("value", element.attr("value") || "");
          _this.submitForm();
          return e.stopPropagation();
        });
      });
    }

    Watcher.prototype.callObservers = function(eventName) {
      var args,
        _this = this;
      args = _.toArray(arguments);
      args.shift();
      return _.each(this.observers[eventName], function(observer) {
        return observer.apply(_this, args);
      });
    };

    Watcher.prototype.observe = function(eventName, func) {
      if (this.observers[eventName] === undefined) {
        this.observers[eventName] = [];
      }
      this.observers[eventName].push(func);
      return this;
    };

    Watcher.prototype.stopObserving = function(eventName, func) {
      this.observers[eventName] = _.select(this.observers[eventName], function() {
        return this !== func;
      });
      return this;
    };

    Watcher.prototype.enableForm = function() {
      return $(":input", this.form).attr("disabled", false);
    };

    Watcher.prototype.disableForm = function() {
      return $(":input", this.form).attr("disabled", true);
    };

    Watcher.prototype.submitForm = function(e) {
      if (!this.options.validate || this.validateForm()) {
        this.callObservers("submit");
        if (this.options.ajax) {
          this.disableForm();
          return this.submitAjax();
        } else {
          this.form.attr("action", this.form.fwData("originalAction"));
          _.defer(_.bind(function() {
            this.form.submit();
            return this.disableForm();
          }, this));
          return false;
        }
      } else {

      }
    };

    Watcher.prototype.validateForm = function() {
      var validated;
      validated = true;
      _.each(this.allElements, function(elements) {
        if (!this.validateElements(elements)) {
          return validated = false;
        }
      }, this);
      return validated;
    };

    Watcher.prototype.validateElements = function(elements, inlineValidating) {
      var input, sanitizedValue, validated;
      input = elements.input;
      validated = true;
      if (input.fwData("validators").length) {
        if (!inlineValidating || !input.fwData("lastValidatedValue") || input.fwData("lastValidatedValue") !== input.val()) {
          input.fwData("lastValidatedValue", input.val());
          Formwatcher.debug("Validating input " + input.attr("name"));
          input.fwData("validationErrors", []);
          validated = _.all(input.fwData("validators"), function(validator) {
            var validationOutput;
            if (input.val() === "" && validator.name !== "Required") {
              Formwatcher.debug("Validating " + validator.name + ". Field was empty so continuing.");
              return true;
            }
            Formwatcher.debug("Validating " + validator.name);
            validationOutput = validator.validate(validator.sanitize(input.val()), input);
            if (validationOutput !== true) {
              validated = false;
              input.fwData("validationErrors").push(validationOutput);
              return false;
            }
            return true;
          });
          if (!validated) {
            _.each(elements, function(element) {
              return element.removeClass("validated");
            });
            if (!inlineValidating) {
              elements.errors.html(input.fwData("validationErrors").join("<br />")).show();
              _.each(elements, function(element) {
                return element.addClass("error");
              });
            }
          } else {
            elements.errors.html("").hide();
            _.each(elements, function(element) {
              element.addClass("validated");
              return element.removeClass("error");
            });
            if (inlineValidating) {
              elements.input.fwData("forceValidationOnChange", true);
            }
          }
        }
        if (!inlineValidating && validated) {
          sanitizedValue = input.fwData("lastValidatedValue");
          _.each(input.fwData("validators"), function(validator) {
            return sanitizedValue = validator.sanitize(sanitizedValue);
          });
          input.val(sanitizedValue);
        }
      } else {
        _.each(elements, function(element) {
          return element.addClass("validated");
        });
      }
      return validated;
    };

    Watcher.prototype.submitAjax = function() {
      var fields, i,
        _this = this;
      Formwatcher.debug("Submitting form via AJAX.");
      fields = {};
      i = 0;
      $(":input", this.form).each(function(input, i) {
        var attributeName;
        input = $(input);
        if (input.fwData("forceSubmission") || input.attr("type") === "checkbox" || input.fwData('changed') || self.options.submitUnchanged) {
          if (input.attr('type') !== 'checkbox' || input.is(':checked')) {
            attributeName = input.attr("name") ? input.attr("name") : "unnamedInput_" + i;
            return fields[attributeName] = input.val();
          }
        }
      });
      if (_.size(fields) === 0 && !this.options.submitFormIfAllUnchanged) {
        return _.defer(_.bind(function() {
          this.enableForm();
          return this.ajaxSuccess();
        }, this));
      } else {
        return $.ajax({
          url: this.form.fwData("originalAction"),
          type: "POST",
          data: fields,
          context: this,
          error: function(request) {
            return _this.callObservers("error", request.response);
          },
          success: function(data) {
            _this.enableForm();
            if (!_this.options.responseCheck(data)) {
              return _this.callObservers("error", data);
            } else {
              _this.callObservers("success", data);
              return _this.ajaxSuccess();
            }
          }
        });
      }
    };

    Watcher.prototype.ajaxSuccess = function() {
      var element, elements, i, isEmpty, _i, _len, _ref, _results;
      _ref = this.allElements;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        elements = _ref[_i];
        Formwatcher.unsetChanged(elements, this);
        if (this.options.resetFormAfterSubmit) {
          Formwatcher.restoreInitialValue(elements);
        } else {
          Formwatcher.storeInitialValue(elements);
        }
        isEmpty = elements.input.val() === null || !elements.input.val();
        _results.push((function() {
          var _results1;
          _results1 = [];
          for (i in elements) {
            element = elements[i];
            if (isEmpty) {
              _results1.push(element.addClass("empty"));
            } else {
              _results1.push(element.removeClass("empty"));
            }
          }
          return _results1;
        })());
      }
      return _results;
    };

    return Watcher;

  })();

  if (typeof window !== "undefined" && window !== null) {
    window.Formwatcher = Formwatcher;
    window.Watcher = Watcher;
  }

  $(document).ready(Formwatcher.scanDocument);

}).call(this);
