// Generated by CoffeeScript 1.3.1
(function(){var e={}.hasOwnProperty,t=function(t,n){function i(){this.constructor=t}for(var r in n)e.call(n,r)&&(t[r]=n[r]);return i.prototype=n.prototype,t.prototype=new 
i,t.__super__=n.prototype,t};Formwatcher.decorators.push(function(e){function n(){return n.__super__.constructor.apply(this,arguments)}return t(n,e),n.prototype.name="DatePicker",n.prototype.description="Shows a date picker to select a date."
,n.prototype.nodeNames=["INPUT"],n.prototype.classNames=["date"],n.prototype.strPad=function(e,t){t==null&&(t=2),e=e.toString();while(e.length<t)e="0"+e;return e},n.prototype.defaultOptions={months:null
,formatDate:function(e,t,n){return[e,this.strPad(t),this.strPad(n)].join("-")},weekStart:0,daysOfWeek:null},n.prototype.decorate=function(e){var t,n;return t={input:e},n=Formwatcher.deepExtend({date:new 
Date(e.val())},this.options),e.calender(n),t},n}(Formwatcher.Decorator))}).call(this);